name: Publish Fedora Toolbox images

on:
  
  release:
    types: [published]

jobs:

  push_to_registry:
    
    name: Push to GitHub Packages
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile.toolbox
          registry: docker.pkg.github.com
          repository: arouene/fedora-toolbox-images/toolbox
          tag_with_ref: true
